name: Check PR labels

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main

jobs:
  check_pr_labels:
    name: Check PR Labels
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/labeler@v4
        with:
	  repo-token: ${{ secrets.GITHUB_TOKEN }}
	  dot: true
	  Infrastructure:
	    - any: ['.github/**', 'CI/**']
