name: Check PR labels

on:
  pull_request:
    branches:
      - main

jobs:
  check_pr_labels:
    name: Check PR Labels
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
	run: python3 CI/check_pr_labels.py --pull_id ${{ github.event.number }} --repository ${{ github.event.repository.name }}
